version: "3.7"

services:
  excalidraw-server:
    container_name: excalidraw-server
    image: git.b0t.at/b0t-at/excalidraw-stack:latest
    restart: always
#    ports:
#      - "3001:80"
    environment:
      NODE_ENV: production
      TZ: Europe/Amsterdam
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.${Service1}.rule=Host(`${Service1URL}`)
      - traefik.http.routers.${Service1}.entrypoints=https
      - traefik.http.routers.${Service1}.service=${Service1}
      - traefik.http.routers.${Service1}.tls.certresolver=letsencrypt
      - traefik.http.services.${Service1}.loadbalancer.server.port=${Service1Port}

  excalidraw-room:
    container_name: excalidraw-room
    image: excalidraw/excalidraw-room:latest
    restart: always
    environment:
      TZ: Europe/Amsterdam
      PORT: 3002
#    ports:
#      - "3002:3002"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.${Service2}.rule=Host(`${Service2URL}`)
      - traefik.http.routers.${Service2}.entrypoints=https
      - traefik.http.routers.${Service2}.service=${Service2}
      - traefik.http.routers.${Service2}.tls.certresolver=letsencrypt
      - traefik.http.services.${Service2}.loadbalancer.server.port=${Service2Port}

  excalidraw-storage-backend:
    container_name: excalidraw-storage
    stdin_open: true
    build:
      context: https://github.com/kitsteam/excalidraw-storage-backend.git#main
      target: production
#    ports:
#      - "3003:8080"
    environment:
      STORAGE_URI: redis://:${REDIS_PASSWORD}@redis:6379
      STORAGE_TTL: 2592000000
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.${Service3}.rule=Host(`${Service3URL}`)
      - traefik.http.routers.${Service3}.entrypoints=https
      - traefik.http.routers.${Service3}.service=${Service3}
      - traefik.http.routers.${Service3}.tls.certresolver=letsencrypt
      - traefik.http.services.${Service3}.loadbalancer.server.port=${Service3Port}

  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - /opt/docker/excalidraw-stack/redis_data:/data
  
networks:
  proxy:
    external: true 
